### ISSUE TITLE
There should be an option to let cache pool handle expiration, instead of having to set expires_at

### ISSUE THREAD

**Issue by ostrolucky** [php-http/cache-plugin#49]
| Q            | A
| ------------ | ---
| Version      | 1.5.0

When creating cache pool (e.g. in Symfony), user must choose default lifetime. When using php-http cache-plugin, user must again configure default_ttl option.

These two options do the same thing. There should be a way to configure cache plugin to let expire cache items organically by cache pool. 

This is problematic, because lot of times I create separate cache pools for each http client and I have to duplicate this configuration and making sure changes in them are propagated to all places.

Furthermore, cache plugin implements expiration functionality by itself unnecessarily. There is no need to store `expiresAt` data, that's what is `$cacheItem->expiresAfter()` call for.

**Comment by dbu** [comment]
https://github.com/php-http/cache-plugin/blob/5ae8a805966987a12f5185897914c2966acdf09e/src/CachePlugin.php#L308 indicates that the default ttl is optional. you can set default_ttl to `null`. the default for default_ttl is `0`. i think 0 leads to no caching at all, if i read the code correctly.

normally, HTTP servers are supposed to provide a max-age or s-maxage to dictate the cache lifetime. if those are present, we should respect them and the default configuration of the cache pool is not relevant.

`expiresAt` is about HTTP, not about the caching implementation. HTTP allows to ask the server if a cached result is still valid. when we find the response in the cache, but expiresAt is past, we ask the server for the response but with the `If-Modified-Since` header. the server can either send us a new anser, or tell with `304 Not Modified` that our cache is still useful. in that case we update the cache lifetime.

because of the if-modified thing, default ttl and cache retention time are not the same. in your use case, you might not need all of this, but the plugin will support it.

does this answer your questions?

**Comment by ostrolucky** [comment]
> i think 0 leads to no caching at all, if i read the code correctly.

Correct. So if no cache header is present, there is no caching by default.

>  There is no need to store expiresAt data, that's what is $cacheItem->expiresAfter() call for.

Ok, I now know why this quote isn't correct, thanks. Plugin, even if cache isn't hit, needs to retrieve last known expiration time and use it to tell the server it doesn't need to return full response if nothing has been changed.

So, it's now clear to me why native cache expiration mechanism isn't used. My root problem though, is that none of the APIs I use work with these cache/expiration headers properly. So all of this is out of equation and I'm ok with just expiring the item whenever cache pool expires it. 

But, analyzing the code of plugin further, I think what I want to do can be achieved by setting
both `default_ttl` and `cache_lifetime` to `null`. Thank you for your answer, it helped me understand how to solve my problem.
